# Generated by Django 2.2 on 2019-12-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='user_who_do',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs_do', to='login_registration.User'),
        ),
    ]
