# Generated by Django 2.2 on 2019-12-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0003_auto_20191213_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cat',
            field=models.CharField(max_length=45),
        ),
    ]
